// VUE-BUSINESS-APP/src/views/GpsSession.vue
<template>

  <div v-if="gpsSessionData.errors" class="alert alert-warning mt-3">
    {{ gpsSessionData.errors }}
  </div>

  <h1>
    <span>GpsSessions</span>
    <RouterLink to="/gps-session-create" class="btn btn-success btn-sm ms-2">+</RouterLink>
  </h1>

  <!-- Filter bar -->
  <div class="card p-3 mb-4 shadow-sm">
    <div class="row g-3 align-items-end">
      <div class="col-md-2">
        <label class="form-label">Min Locations</label>
        <input v-model.number="filters.minLocationsCount" type="number" class="form-control" />
      </div>
      <div class="col-md-2">
        <label class="form-label">Min Duration</label>
        <input v-model.number="filters.minDuration" type="number" class="form-control" />
      </div>
      <div class="col-md-2">
        <label class="form-label">Min Distance</label>
        <input v-model.number="filters.minDistance" type="number" class="form-control" />
      </div>
      <div class="col-md-3">
        <label class="form-label">From Date</label>
        <input v-model="filters.fromDateTime" type="datetime-local" class="form-control" />
      </div>
      <div class="col-md-3">
        <label class="form-label">To Date</label>
        <input v-model="filters.toDateTime" type="datetime-local" class="form-control" />
      </div>
    </div>
    <div class="d-flex justify-content-end mt-3">
      <button class="btn btn-secondary btn-sm me-2" @click="resetFilters">Reset</button>
      <button class="btn btn-primary btn-sm" @click="fetchFilteredData">Filter</button>
    </div>
  </div>

  <!-- Table -->
  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>RecordedAt</th>
      <th>Locations</th>
      <th>User</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <tr v-for="item in gpsSessionData.data" :key="item.id">
      <td>{{ item.name }}</td>
      <td>{{ item.description }}</td>
      <td>{{ formatDate(item.recordedAt) }}</td>
      <td>{{ item.gpsLocationsCount }}</td>
      <td>{{ item.userFirstLastName }}</td>
      <td>
        <RouterLink :to="`/gps-session-edit/${item.id}`" class="text-warning">Edit</RouterLink> |
        <RouterLink :to="`/gps-session-details/${item.id}`">Details</RouterLink> |
        <RouterLink :to="`/gps-session-delete/${item.id}`" class="text-danger">Delete</RouterLink>
      </td>
    </tr>
    </tbody>
  </table>
</template>

<script setup lang="ts">
import {onMounted, reactive, ref} from "vue";
import {GpsSessionService} from "../service/GpsSessionService.ts";
import type {IResultObject} from "../types/IResultObject.ts";
import type {IGpsSession} from "../domain/IGpsSession.ts";

const gpsSessionService = new GpsSessionService();
const gpsSessionData = reactive<IResultObject<IGpsSession[]>>({});
const requestIsOngoing = ref(false);

function getDefaultFilters() {
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  const toISOStringLocal = (date: Date) => date.toISOString().slice(0, 16);

  return {
    minLocationsCount: 0,
    minDuration: 0,
    minDistance: 0,
    fromDateTime: toISOStringLocal(yesterday),
    toDateTime: toISOStringLocal(new Date())
  }
}

const filters = reactive(getDefaultFilters());

function resetFilters() {
  const defaults = getDefaultFilters();
  filters.minLocationsCount = defaults.minLocationsCount;
  filters.minDuration = defaults.minDuration;
  filters.minDistance = defaults.minDistance;
  filters.fromDateTime = defaults.fromDateTime;
  filters.toDateTime = defaults.toDateTime;

  fetchFilteredData();
}

async function fetchFilteredData() {
  requestIsOngoing.value = true;
  try {
    const result = await gpsSessionService.getFilteredAsync({
      minLocationsCount: filters.minLocationsCount,
      minDuration: filters.minDuration,
      minDistance: filters.minDistance,
      fromDateTime: filters.fromDateTime ? new Date(filters.fromDateTime).toISOString().slice(0, 16) : undefined,
      toDateTime: filters.toDateTime ? new Date(filters.toDateTime).toISOString().slice(0, 16) : undefined,
    });
    gpsSessionData.data = result.data;
    gpsSessionData.errors = result.errors;
  } catch (error) {
    console.error("Error fetching filtered data", error);
  } finally {
    requestIsOngoing.value = false;
  }
}

function formatDate(isoString: string): string {
  const date = new Date(isoString);
  return date.toLocaleString("et-EE", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  });
}


// const fetchPageData = async () => {
//   requestIsOngoing.value = true;
//   try{
//     const result = await gpsSessionService.getAllAsync();
//     console.log(result.data);
//
//     gpsSessionData.data = result.data;
//     gpsSessionData.errors = result.errors;
//
//   } catch(error){
//     console.error('Error fetching data: ', error);
//   } finally {
//     requestIsOngoing.value = false;
//   }
// };

onMounted(async () => {
  await fetchFilteredData();
});
</script>

// react-business-app/src/app/gps-session/page.tsx
"use client"
import { useEffect, useState } from "react";
import Link from "next/link";
import { GpsSessionService } from "@/service/GpsSessionService";
import { IGpsSession } from "@/domain/IGpsSession";
import { IResultObject } from "@/types/IResultObject";

function toISOStringLocal(date: Date): string {
    return date.toISOString().slice(0, 16);
}

const getDefaultFilters = () => {
    const fromDate = new Date('2020-01-01T00:00:00.000Z');
    const toDate = new Date(Date.now() + 3 * 60 * 60 * 1000); // UTC + 3h

    return {
        minLocationsCount: 0,
        minDuration: 0,
        minDistance: 0,
        fromDateTime: toISOStringLocal(fromDate),
        toDateTime: toISOStringLocal(toDate)
    };
};

export default function GpsSessionsPage() {
    const gpsSessionService = new GpsSessionService()
    const [gpsSessionData, setGpsSessionData] = useState<IResultObject<IGpsSession[]>>({});
    const [filters, setFilters] = useState(getDefaultFilters());
    const [requestIsOngoing, setRequestIsOngoing] = useState(false);

    const fetchFilteredData = async () => {
        setRequestIsOngoing(true);
        try {
            const result = await gpsSessionService.getFilteredAsync(filters);
            setGpsSessionData({
                data: result.data,
                errors: result.errors
            });
        } catch (error) {
            console.error("Error fetching filtered data", error);
        } finally {
            setRequestIsOngoing(false);
        }
    };

    const resetFilters = () => {
        setFilters(getDefaultFilters());
        fetchFilteredData();
    };

    useEffect(() => {
        fetchFilteredData();
    }, []);

    const formatDate = (isoString: string): string => {
        const date = new Date(isoString);
        return date.toLocaleString("et-EE", {
            day: "2-digit",
            month: "2-digit",
            year: "numeric",
            hour: "2-digit",
            minute: "2-digit"
        });
    };

    return (
        <div className="container mt-4">
            {gpsSessionData.errors && (
                <div className="alert alert-warning mt-3">
                    {gpsSessionData.errors}
                </div>
            )}

            <h1>
                <span>GpsSessions</span>
                <Link href="/gps-session-create" className="btn btn-success btn-sm ms-2">+</Link>
            </h1>

            <div className="card p-3 mb-4 shadow-sm">
                <div className="row g-3 align-items-end">
                    <div className="col-md-2">
                        <label className="form-label">Min Locations</label>
                        <input
                            type="number"
                            className="form-control"
                            value={filters.minLocationsCount}
                            onChange={(e) => setFilters({ ...filters, minLocationsCount: Number(e.target.value) })}
                        />
                    </div>
                    <div className="col-md-2">
                        <label className="form-label">Min Duration</label>
                        <input
                            type="number"
                            className="form-control"
                            value={filters.minDuration}
                            onChange={(e) => setFilters({ ...filters, minDuration: Number(e.target.value) })}
                        />
                    </div>
                    <div className="col-md-2">
                        <label className="form-label">Min Distance</label>
                        <input
                            type="number"
                            className="form-control"
                            value={filters.minDistance}
                            onChange={(e) => setFilters({ ...filters, minDistance: Number(e.target.value) })}
                        />
                    </div>
                    <div className="col-md-3">
                        <label className="form-label">From Date</label>
                        <input
                            type="datetime-local"
                            className="form-control"
                            value={filters.fromDateTime}
                            onChange={(e) => setFilters({ ...filters, fromDateTime: e.target.value })}
                        />
                    </div>
                    <div className="col-md-3">
                        <label className="form-label">To Date</label>
                        <input
                            type="datetime-local"
                            className="form-control"
                            value={filters.toDateTime}
                            onChange={(e) => setFilters({ ...filters, toDateTime: e.target.value })}
                        />
                    </div>
                </div>
                <div className="d-flex justify-content-end mt-3">
                    <button className="btn btn-secondary btn-sm me-2" onClick={resetFilters}>Reset</button>
                    <button className="btn btn-primary btn-sm" onClick={fetchFilteredData}>Filter</button>
                </div>
            </div>

            <table className="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>RecordedAt</th>
                    <th>Locations</th>
                    <th>User</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {gpsSessionData.data?.map((item) => (
                    <tr key={item.id}>
                        <td>{item.name}</td>
                        <td>{item.description}</td>
                        <td>{formatDate(item.recordedAt)}</td>
                        <td>{item.gpsLocationsCount}</td>
                        <td>{item.userFirstLastName}</td>
                        <td>
                            <Link href={`/gps-session-edit/${item.id}`} className="text-warning mx-1"><i
                                className="bi bi-pencil"></i>
                            </Link><br/>
                            <Link href={`/gps-session-details/${item.id}`} className="mx-1">
                                <i className="bi bi-info-circle"></i>
                            </Link><br/>
                            <Link href={`/gps-session-delete/${item.id}`} className="text-danger mx-1">
                                <i className="bi bi-trash"></i>
                            </Link>
                        </td>
                    </tr>
                ))}
                </tbody>
            </table>
        </div>
    );
}
