// react-business-app/src/app/gps-session-create/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { IGpsSessionCreateRequest } from '@/domain/IGpsSessionRequest';
import type { IResultObject } from '@/types/IResultObject';
import { GpsSessionService } from '@/service/GpsSessionService';
import {IGpsSessionResponse} from "@/domain/IGpsSessionResponse";

export default function CreateGpsSessionPage() {
    const router = useRouter();
    const gpsSessionService = new GpsSessionService();

    const [requestIsOngoing, setRequestIsOngoing] = useState(false);
    const [gpsSessionData, setGpsSessionData] = useState<IResultObject<IGpsSessionResponse>>({});
    const [gpsSession, setGpsSession] = useState<IGpsSessionCreateRequest>({
        name: '',
        description: '',
        gpsSessionTypeId: '',
        recordedAt: '',
        paceMin: 60,
        paceMax: 61,
    });

    const handleChange = (field: keyof IGpsSessionCreateRequest, value: string | number) => {
        setGpsSession(prev => ({ ...prev, [field]: value }));
    };

    const cancel = () => {
        router.push('/gps-session');
    };

    const postGpsSession = async () => {
        setRequestIsOngoing(true);
        console.log(gpsSession)
        try {
            const result = await gpsSessionService.addAsync(gpsSession);
            setGpsSessionData(result);

            if (!result.errors) {
                router.push('/gps-session');
            }
        } catch (error) {
            console.error('Error creating session:', error);
        } finally {
            setRequestIsOngoing(false);
        }
    };

    const doCreate = async (e: React.FormEvent) => {
        e.preventDefault();
        await postGpsSession();
    };

    return (
        <div className="container mt-4">
            {gpsSessionData.errors && typeof gpsSessionData.errors === 'object' && (
                <div className="alert alert-warning" role="alert">
                    <ul className="mb-0">
                        {Object.entries(gpsSessionData.errors).map(([field, message]) => (
                            <li key={field}>{String(message)}</li>
                        ))}
                    </ul>
                </div>
            )}

            {gpsSessionData.errors && typeof gpsSessionData.errors === 'string' && (
                <div className="alert alert-warning" role="alert">
                    {gpsSessionData.errors}
                </div>
            )}
            <div className="card shadow-sm p-4">
                <h2 className="mb-4">Create New GpsSession</h2>

                <form onSubmit={doCreate}>
                    <div className="row mb-3">
                        <label htmlFor="Input_Name" className="col-sm-3 col-form-label fw-bold">Name</label>
                        <div className="col-sm-9">
                            <input
                                id="Input_Name"
                                type="text"
                                className="form-control"
                                value={gpsSession.name}
                                onChange={e => handleChange('name', e.target.value)}
                            />
                        </div>
                    </div>

                    <div className="row mb-3">
                        <label htmlFor="Input_Description" className="col-sm-3 col-form-label fw-bold">Description</label>
                        <div className="col-sm-9">
                            <input
                                id="Input_Description"
                                type="text"
                                className="form-control"
                                value={gpsSession.description}
                                onChange={e => handleChange('description', e.target.value)}
                            />
                        </div>
                    </div>

                    <div className="row mb-3">
                        <label htmlFor="Input_GpsSessionTypeId" className="col-sm-3 col-form-label fw-bold">Session Type</label>
                        <div className="col-sm-9">
                            <input
                                id="Input_GpsSessionTypeId"
                                type="text"
                                className="form-control"
                                value={gpsSession.gpsSessionTypeId}
                                onChange={e => handleChange('gpsSessionTypeId', e.target.value)}
                            />
                        </div>
                    </div>

                    <div className="row mb-3">
                        <label htmlFor="Input_RecordedAt" className="col-sm-3 col-form-label fw-bold">Recorded At</label>
                        <div className="col-sm-9">
                            <input
                                id="Input_RecordedAt"
                                type="datetime-local"
                                className="form-control"
                                value={gpsSession.recordedAt}
                                onChange={e => handleChange('recordedAt', e.target.value)}
                            />
                        </div>
                    </div>

                    <div className="row mb-3">
                        <label htmlFor="Input_PaceMin" className="col-sm-3 col-form-label fw-bold">Pace Min</label>
                        <div className="col-sm-9">
                            <input
                                id="Input_PaceMin"
                                type="number"
                                className="form-control"
                                value={gpsSession.paceMin}
                                onChange={e => handleChange('paceMin', Number(e.target.value))}
                            />
                        </div>
                    </div>

                    <div className="row mb-4">
                        <label htmlFor="Input_PaceMax" className="col-sm-3 col-form-label fw-bold">Pace Max</label>
                        <div className="col-sm-9">
                            <input
                                id="Input_PaceMax"
                                type="number"
                                className="form-control"
                                value={gpsSession.paceMax}
                                onChange={e => handleChange('paceMax', Number(e.target.value))}
                            />
                        </div>
                    </div>

                    <div className="row">
                        <div className="offset-sm-3 col-sm-9 d-flex justify-content-end">
                            <button type="button" className="btn btn-outline-secondary" onClick={cancel}>
                                Cancel
                            </button>
                            <button type="submit" className="btn btn-success ms-2" disabled={requestIsOngoing}>
                                Create
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    );
}

// VUE-BUSINESS-APP/src/views/GpsSessionCreate.vue
<template>
  <div v-if="gpsSessionData.errors" class="alert alert-warning" role="alert">
    {{ gpsSessionData.errors }}
  </div>

  <div class="container mt-4">
    <div class="card shadow-sm p-4">
      <h2 class="mb-4">Create New GpsSession</h2>

      <form @submit.prevent="doCreate">
        <div class="row mb-3">
          <label for="Input_Name" class="col-sm-3 col-form-label fw-bold">Name</label>
          <div class="col-sm-9">
            <input v-model="gpsSession.name" id="Input_Name" type="text" class="form-control" />
          </div>
        </div>

        <div class="row mb-3">
          <label for="Input_Description" class="col-sm-3 col-form-label fw-bold">Description</label>
          <div class="col-sm-9">
            <input v-model="gpsSession.description" id="Input_Description" type="text" class="form-control" />
          </div>
        </div>

        <div class="row mb-3">
          <label for="Input_GpsSessionTypeId" class="col-sm-3 col-form-label fw-bold">Session Type</label>
          <div class="col-sm-9">
            <input v-model="gpsSession.gpsSessionTypeId" id="Input_GpsSessionTypeId" type="text" class="form-control" />
          </div>
        </div>

        <div class="row mb-3">
          <label for="Input_RecordedAt" class="col-sm-3 col-form-label fw-bold">Recorded At</label>
          <div class="col-sm-9">
            <input v-model="gpsSession.recordedAt" id="Input_RecordedAt" type="datetime-local" class="form-control" />
          </div>
        </div>

        <div class="row mb-3">
          <label for="Input_PaceMin" class="col-sm-3 col-form-label fw-bold">Pace Min</label>
          <div class="col-sm-9">
            <input v-model.number="gpsSession.paceMin" id="Input_PaceMin" type="number" class="form-control" />
          </div>
        </div>

        <div class="row mb-4">
          <label for="Input_PaceMax" class="col-sm-3 col-form-label fw-bold">Pace Max</label>
          <div class="col-sm-9">
            <input v-model.number="gpsSession.paceMax" id="Input_PaceMax" type="number" class="form-control" />
          </div>
        </div>

        <div class="row">
          <div class="offset-sm-3 col-sm-9 d-flex justify-content-end">
            <button type="button" class="btn btn-outline-secondary" @click="cancel">Cancel</button>
            <button type="submit" class="btn btn-success ms-2">Create</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import {reactive, ref} from "vue";
import type {IResultObject} from "../types/IResultObject.ts";
import type {IGpsSession} from "../domain/IGpsSession.ts";
import {GpsSessionService} from "../service/GpsSessionService.ts";
import type {IGpsSessionRequest} from "../domain/IGpsSessionRequest.ts";
import router from "../router";

const requestIsOngoing = ref(false);
const gpsSessionData = reactive<IResultObject<IGpsSession>>({});
const gpsSessionService = new GpsSessionService();

// TODO: change to IGpsSessionCreateRequest?
const gpsSession = reactive<IGpsSessionRequest>({
  name: '',
  description: '',
  gpsSessionTypeId: '',
  recordedAt: '',
  paceMin: 60,
  paceMax: 61,
});

const postGpsSession = async () => {
  requestIsOngoing.value = true;
  try{
    const result = await gpsSessionService.addAsync(gpsSession);
    console.log(result.data);

    gpsSessionData.data = result.data;
    gpsSessionData.errors = result.errors;

    // await router.push(`/gps-session-edit/${result.data?.id}`)
    // await router.push(`/gps-session-delete/${result.data?.id}`)

    await router.push('/')

  } catch(error){
    console.error('Error fetching data: ', error);
  } finally {
    requestIsOngoing.value = false;
  }
}

const doCreate = async () => {
  await postGpsSession();
}

function returnToSessionsPage(): void {
  router.push('/gps-session');
}

function cancel() {
  returnToSessionsPage();
}
</script>
