// react-business-app/src/components/Header.tsx
// components/Header.tsx
"use client";

import Link from "next/link";
import {useContext, useState} from "react";
import {BaseContext} from "@/context/BaseContext";

export default function Header() {
    const [isCollapsed, setIsCollapsed] = useState(true);

    const context = useContext(BaseContext);

    return (
        <header>
            <nav className="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div className="container">
                    <Link className="navbar-brand" href="/">Sportmap</Link>
                    <button
                        className="navbar-toggler"
                        type="button"
                        aria-controls="navbarSupportedContent"
                        aria-expanded={!isCollapsed}
                        aria-label="Toggle navigation"
                        onClick={() => setIsCollapsed(!isCollapsed)}
                    >
                        <span className="navbar-toggler-icon" />
                    </button>
                    <div className={`navbar-collapse collapse d-sm-inline-flex justify-content-between ${!isCollapsed ? "show" : ""}`}>
                        <ul className="navbar-nav flex-grow-1">
                            <li className="nav-item">
                                <Link className="nav-link text-dark" href="/">Home</Link>
                            </li>
                            <li className="nav-item">
                                <Link className="nav-link text-dark" href="/page1">Types</Link>
                            </li>
                            <li className="nav-item">
                                <Link className="nav-link text-dark" href="/gps-session">GpsSessions</Link>
                            </li>
                        </ul>
                        {!context?.isAuthenticated ? (
                            <ul className="navbar-nav">
                                <li className="nav-item">
                                    <Link className="nav-link text-dark" href="/register">Register</Link>
                                </li>
                                <li className="nav-item">
                                    <Link className="nav-link text-dark" href="/login">Login</Link>
                                </li>
                            </ul>
                        ) : (
                            <ul className="navbar-nav">
                                <li className="nav-item">
                                    <Link className="nav-link text-dark" href="#">Logout</Link>
                                </li>
                            </ul>
                        )}
                    </div>
                </div>
            </nav>
        </header>
    );
}

// VUE-BUSINESS-APP/src/navigation/Header.vue
<template>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      <div class="container">
        <a class="navbar-brand" href="/">Sportmap</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <ul class="navbar-nav flex-grow-1">

            <li class="nav-item">
              <RouterLink class="nav-link text-dark" to="/">Home</RouterLink>
            </li>

            <li class="nav-item">
              <RouterLink class="nav-link text-dark" to="/page1">Types</RouterLink>
            </li>

            <li class="nav-item">
              <RouterLink class="nav-link text-dark" to="/gps-session">GpsSessions</RouterLink>
            </li>
          </ul>

          <ul v-if="!useStore.jwt" class="navbar-nav">
            <li class="nav-item">
              <RouterLink class="nav-link text-dark"  to="/Register">Register</RouterLink>
            </li>
            <li class="nav-item">
              <RouterLink class="nav-link text-dark"  to="/Login">Login</RouterLink>
            </li>
          </ul>
          <ul v-else>
            <li class="nav-item">
              <RouterLink class="nav-link text-dark"  to="#">Logout</RouterLink>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
</template>

<script setup lang="ts">
import {RouterLink} from "vue-router";
import {useUserDataStore} from "../stores/userDataStore.ts";

const useStore = useUserDataStore();

</script>
